version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: knu-gpt-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${DATABASE}
      TZ: Asia/Seoul
    volumes:
      - /home/ubuntu/volumes/mysql:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-p${MYSQL_PASSWORD}" ]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - knu-gpt-net

  redis:
    image: redis:7.2
    container_name: knu-gpt-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /home/ubuntu/volumes/redis:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - knu-gpt-net

  mongodb:
    image: mongo:6.0
    container_name: knu-gpt-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
      TZ: Asia/Seoul
    volumes:
      - /home/ubuntu/volumes/mongo:/data/db
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - knu-gpt-net

  backend-app:
    image: himodu/knugpt-server
    container_name: knu-gpt-server
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    environment:
      - SPRING_ACTIVE=${SPRING_ACTIVE}
      - SPRING_DATASOURCE_URL=${DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
      - MONGO_DATABASE=${MONGO_DATABASE}
      - EMAIL=${EMAIL}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - knu-gpt-net

networks:
  knu-gpt-net:
    driver: bridge